name: Tweeter_posting_workflow 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *' # Runs Bot every 3 hours.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
          cache: 'pip'
          
      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Run Bot
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}  
        run: python3 google_bot.py
